### ISSUE TITLE
Deal with the LESS duplication in _author.less

### ISSUE THREAD

**Issue by Manvel** [Manvel/blog#15]
```css
.post header
{
  .author
  {
    .avatar
    {
      width: 45px;
    }
    p:not(:last-of-type), h1
    {
      margin-bottom: 5px;
    }
    .social
    {
      display: none;
    }
  }
}

@media (max-width: @tablet-width)
{
  header
  {
    .author
    {
      .avatar
      {
        width: 45px;
      }
      p:not(:last-of-type), h1
      {
        margin-bottom: 5px;
      }
      .social
      {
        display: none;
      }
    }
  }
}
```
